import type {
  AppChromeCopy,
  InferPageCopy,
  LocaleCopyMap,
  ParameterPageCopy,
  StepFlowCopy,
  TrainPageCopy,
} from './copyTypes.ts';

export const APP_CHROME_COPY: LocaleCopyMap<AppChromeCopy> = {
  zh: {
    brandTitle: 'ScaleAtlas',
    nav: [
      { to: '/', label: '参数计算', tone: 'parameter' },
      { to: '/train', label: '训练', tone: 'train' },
      { to: '/infer', label: '推理', tone: 'infer' },
    ],
  },
  en: {
    brandTitle: 'ScaleAtlas',
    nav: [
      { to: '/', label: 'Parameters', tone: 'parameter' },
      { to: '/train', label: 'Training', tone: 'train' },
      { to: '/infer', label: 'Inference', tone: 'infer' },
    ],
  },
};

export const STEP_FLOW_COPY: LocaleCopyMap<StepFlowCopy> = {
  zh: {
    parameter: {
      pageTitle: '参数计算',
      steps: {
        model: '模型',
        result: '结果',
        advanced: '高级',
      },
    },
    train: {
      pageTitle: '训练',
      steps: {
        model: '模型',
        task: '训练任务',
        hardware: '硬件',
        result: '结果',
      },
    },
    infer: {
      pageTitle: '推理',
      steps: {
        model: '模型',
        service: '服务参数',
        hardware: '硬件',
        result: '结果',
      },
    },
  },
  en: {
    parameter: {
      pageTitle: 'Parameters',
      steps: {
        model: 'Model',
        result: 'Result',
        advanced: 'Advanced',
      },
    },
    train: {
      pageTitle: 'Training',
      steps: {
        model: 'Model',
        task: 'Task',
        hardware: 'Hardware',
        result: 'Result',
      },
    },
    infer: {
      pageTitle: 'Inference',
      steps: {
        model: 'Model',
        service: 'Service',
        hardware: 'Hardware',
        result: 'Result',
      },
    },
  },
};

export const PARAMETER_PAGE_COPY: LocaleCopyMap<ParameterPageCopy> = {
  zh: {
    pageTitle: '参数计算',
    pageDescription: '默认优先展示模型骨架，只有点击节点时才展开内部结构。',
    modelSectionTitle: '模型配置',
    modelSectionSummary: '输入完成后这块默认折叠，需要修改时再展开。',
    modelSectionToggle: {
      open: '展开模型配置',
      close: '收起模型配置',
    },
    modeLabel: '模型来源',
    modeOptions: [
      { value: 'custom', label: '自定义', note: '手工输入结构字段' },
      { value: 'config', label: '复制 Config', note: '粘贴 config.json' },
    ],
    presetLabel: '模型预设',
    presetPlaceholder: '选择模型预设...',
    modelType: '模型类型',
    modelName: '模型名称',
    hiddenSize: 'Hidden Size',
    layers: '层数',
    attentionHeads: 'Attention Heads',
    kvHeads: 'KV Heads',
    intermediateSize: 'Intermediate Size',
    vocabSize: 'Vocab Size',
    moeTitle: 'MoE',
    experts: 'Experts',
    expertsPerToken: 'Experts Per Token',
    multimodalTitle: 'Multimodal',
    visionHiddenSize: 'Vision Hidden Size',
    visionLayers: 'Vision Layers',
    projectorHiddenSize: 'Projector Hidden Size',
    coreMetrics: {
      params: '参数量',
      bf16: 'BF16 权重显存',
      structure: '结构类型',
    },
    summary: {
      source: '结构来源',
      imported: '来自 config.json',
      manual: '手工输入',
      waiting: '等待模型输入',
    },
    architectureTitle: '模型骨架',
    overviewTitle: '骨架说明',
    overviewHint: '默认只显示骨架。点击节点后才展开该节点内部结构。',
    skeletonLegend: '主干骨架',
    branchLegend: '侧支接入',
    clickHint: '点击节点展开内部结构',
    configSummaryFields: {
      layers: '层数',
      hidden: 'Hidden',
      experts: 'Experts',
      multimodal: '多模态',
    },
    skeletonDetailHeaders: {
      module: '模块',
      params: '参数量',
      memory: 'BF16',
      share: '占比',
    },
    precisionTitle: '权重显存',
    advancedTitle: '高级',
    advancedToggle: {
      open: '展开高级',
      close: '收起高级',
    },
    invalidSharding: '非法切分约束',
    waitingStructure: '等待模型结构',
    waitingConstraint: '等待有效结构',
    structureTypes: {
      dense: 'Dense',
      moe: 'MoE',
      multimodal: 'Multimodal',
      tts: 'TTS',
    },
    candidateLabels: {
      tp: 'TP 候选',
      pp: 'PP 候选',
      ep: 'EP 候选',
    },
  },
  en: {
    pageTitle: 'Parameters',
    pageDescription: 'Show the model skeleton first. Internal structure only appears after clicking a node.',
    modelSectionTitle: 'Model Config',
    modelSectionSummary: 'This section collapses once the config is ready and only reopens when you need to edit it.',
    modelSectionToggle: {
      open: 'Show model config',
      close: 'Hide model config',
    },
    modeLabel: 'Source',
    modeOptions: [
      { value: 'custom', label: 'Custom', note: 'Enter structure fields' },
      { value: 'config', label: 'Paste Config', note: 'Paste config.json' },
    ],
    presetLabel: 'Model Preset',
    presetPlaceholder: 'Select preset...',
    modelType: 'Model Type',
    modelName: 'Model Name',
    hiddenSize: 'Hidden Size',
    layers: 'Layers',
    attentionHeads: 'Attention Heads',
    kvHeads: 'KV Heads',
    intermediateSize: 'Intermediate Size',
    vocabSize: 'Vocab Size',
    moeTitle: 'MoE',
    experts: 'Experts',
    expertsPerToken: 'Experts Per Token',
    multimodalTitle: 'Multimodal',
    visionHiddenSize: 'Vision Hidden Size',
    visionLayers: 'Vision Layers',
    projectorHiddenSize: 'Projector Hidden Size',
    coreMetrics: {
      params: 'Params',
      bf16: 'BF16 Weight Memory',
      structure: 'Structure',
    },
    summary: {
      source: 'Source',
      imported: 'From config.json',
      manual: 'Manual input',
      waiting: 'Waiting for model input',
    },
    architectureTitle: 'Model Skeleton',
    overviewTitle: 'Skeleton Note',
    overviewHint: 'Only the skeleton is visible by default. Click a node to reveal its internal structure.',
    skeletonLegend: 'Main Skeleton',
    branchLegend: 'Side Branch',
    clickHint: 'Click a node to reveal internals',
    configSummaryFields: {
      layers: 'Layers',
      hidden: 'Hidden',
      experts: 'Experts',
      multimodal: 'Multimodal',
    },
    skeletonDetailHeaders: {
      module: 'Module',
      params: 'Params',
      memory: 'BF16',
      share: 'Share',
    },
    precisionTitle: 'Weight Memory',
    advancedTitle: 'Advanced',
    advancedToggle: {
      open: 'Show advanced',
      close: 'Hide advanced',
    },
    invalidSharding: 'Invalid Sharding',
    waitingStructure: 'Waiting for structure',
    waitingConstraint: 'Waiting for valid structure',
    structureTypes: {
      dense: 'Dense',
      moe: 'MoE',
      multimodal: 'Multimodal',
      tts: 'TTS',
    },
    candidateLabels: {
      tp: 'TP Candidates',
      pp: 'PP Candidates',
      ep: 'EP Candidates',
    },
  },
};

export const TRAIN_PAGE_COPY: LocaleCopyMap<TrainPageCopy> = {
  zh: {
    pageTitle: '训练',
    pageDescription: '按 模型 -> 训练任务 -> 硬件 -> 结果 固定顺序组织，首屏只回答能不能训、峰值显存、推荐并行和吞吐。',
    modelTitle: '模型',
    taskTitle: '训练任务',
    hardwareTitle: '硬件',
    resultTitle: '结果',
    preset: '模型预设',
    modelType: '模型类型',
    modelName: '模型名称',
    hiddenSize: 'Hidden Size',
    layers: '层数',
    attentionHeads: '注意力头数',
    kvHeads: 'KV 头数',
    ffnDim: 'FFN 中间层维度',
    vocabSize: '词表大小',
    moeTitle: 'MoE',
    moeFields: {
      experts: '专家数',
      expertsPerToken: '每 Token 专家数',
    },
    multimodalTitle: '多模态',
    multimodalFields: {
      visionHiddenSize: '视觉 Hidden Size',
      visionLayers: '视觉层数',
    },
    ttsTitle: 'TTS',
    ttsFields: {
      textEncoderHidden: '文本编码器 Hidden Size',
      acousticDecoderHidden: '声学解码器 Hidden Size',
    },
    trainingType: '训练类型',
    precision: '精度',
    seqLen: '序列长度',
    globalBatch: 'Global Batch Size',
    microBatch: 'Micro Batch Size',
    optimizer: '训练增强项',
    optimizerOptions: {
      flashAttention: 'Flash Attention',
      optimizerOffload: 'Optimizer Offload',
    },
    recomputation: '重计算策略',
    loraTitle: 'LoRA',
    loraRank: 'LoRA Rank',
    gpuType: 'GPU 型号',
    gpuMemory: 'GPU 显存 (GB)',
    interconnect: '互联方式',
    gpusPerNode: '单机 GPU 数',
    nodeCount: '节点数',
    totalGpu: '总 GPU',
    advancedToggle: {
      open: '展开高级并行',
      close: '收起高级并行',
    },
    parallelFields: {
      tp: 'TP',
      pp: 'PP',
      dp: 'DP',
      ep: 'EP',
      zeroStage: 'ZeRO Stage',
    },
    actionCopy: {
      fillModel: '请填写模型配置',
      run: '开始训练计算',
      empty: '填写上面三步后开始训练计算。',
    },
    statusCopy: {
      fit: '能训',
      blocked: '不能训',
      badgeFit: '可训练',
      badgeBlocked: '训练受限',
    },
    parallelValidation: '并行切分校验',
    resultSummary: {
      canRun: '能不能训',
      peakMemory: '峰值显存',
      parallel: '推荐并行',
      throughput: '吞吐',
    },
    memoryBreakdown: '显存拆解',
    memoryLabels: {
      params: '参数',
      grads: '梯度',
      optimizer: '优化器',
      activation: '激活',
    },
    mappingTitle: '机器切分映射',
    mappingDescription: '用着色块图标出 stage、权重承载和副本关系。',
    recommendationTitle: '建议',
  },
  en: {
    pageTitle: 'Training',
    pageDescription: 'Fixed Model -> Task -> Hardware -> Result flow. The first screen answers runnability, peak memory, parallel, and throughput.',
    modelTitle: 'Model',
    taskTitle: 'Task',
    hardwareTitle: 'Hardware',
    resultTitle: 'Result',
    preset: 'Model Preset',
    modelType: 'Model Type',
    modelName: 'Model Name',
    hiddenSize: 'Hidden Size',
    layers: 'Layers',
    attentionHeads: 'Attention Heads',
    kvHeads: 'KV Heads',
    ffnDim: 'FFN Intermediate',
    vocabSize: 'Vocab Size',
    moeTitle: 'MoE',
    moeFields: {
      experts: 'Experts',
      expertsPerToken: 'Experts / Token',
    },
    multimodalTitle: 'Multimodal',
    multimodalFields: {
      visionHiddenSize: 'Vision Hidden Size',
      visionLayers: 'Vision Layers',
    },
    ttsTitle: 'TTS',
    ttsFields: {
      textEncoderHidden: 'Text Encoder Hidden',
      acousticDecoderHidden: 'Acoustic Decoder Hidden',
    },
    trainingType: 'Training Type',
    precision: 'Precision',
    seqLen: 'Sequence Length',
    globalBatch: 'Global Batch Size',
    microBatch: 'Micro Batch Size',
    optimizer: 'Training Options',
    optimizerOptions: {
      flashAttention: 'Flash Attention',
      optimizerOffload: 'Optimizer Offload',
    },
    recomputation: 'Recomputation',
    loraTitle: 'LoRA',
    loraRank: 'LoRA Rank',
    gpuType: 'GPU Type',
    gpuMemory: 'GPU Memory (GB)',
    interconnect: 'Interconnect',
    gpusPerNode: 'GPUs / Node',
    nodeCount: 'Nodes',
    totalGpu: 'Total GPU',
    advancedToggle: {
      open: 'Show advanced parallel',
      close: 'Hide advanced parallel',
    },
    parallelFields: {
      tp: 'TP',
      pp: 'PP',
      dp: 'DP',
      ep: 'EP',
      zeroStage: 'ZeRO Stage',
    },
    actionCopy: {
      fillModel: 'Please fill model config',
      run: 'Run training plan',
      empty: 'Complete the first three steps and run the training plan.',
    },
    statusCopy: {
      fit: 'Fit',
      blocked: 'Blocked',
      badgeFit: 'Runnable',
      badgeBlocked: 'Blocked',
    },
    parallelValidation: 'Parallel Validation',
    resultSummary: {
      canRun: 'Can Train',
      peakMemory: 'Peak Memory',
      parallel: 'Recommended Parallel',
      throughput: 'Throughput',
    },
    memoryBreakdown: 'Memory Breakdown',
    memoryLabels: {
      params: 'Params',
      grads: 'Grads',
      optimizer: 'Optimizer',
      activation: 'Activation',
    },
    mappingTitle: 'Machine Split Map',
    mappingDescription: 'Color blocks show stage placement, weight placement, and replicas.',
    recommendationTitle: 'Recommendations',
  },
};

export const INFER_PAGE_COPY: LocaleCopyMap<InferPageCopy> = {
  zh: {
    pageTitle: '推理',
    pageDescription: '按 模型 -> 服务参数 -> 硬件 -> 结果 固定顺序组织，首屏直接回答能否部署、安全并发、峰值显存和推荐并行。',
    modelTitle: '模型',
    serviceTitle: '服务参数',
    hardwareTitle: '硬件',
    resultTitle: '结果',
    preset: '模型预设',
    modelType: '模型类型',
    modelName: '模型名称',
    hiddenSize: 'Hidden Size',
    layers: '层数',
    attentionHeads: '注意力头数',
    kvHeads: 'KV 头数',
    ffnDim: 'FFN 中间层维度',
    vocabSize: '词表大小',
    moeTitle: 'MoE',
    moeFields: {
      experts: '专家数',
      expertsPerToken: '每 Token 专家数',
    },
    engine: '推理引擎',
    mode: '部署模式',
    modeOptions: {
      offline: '离线批量',
      online: '在线服务',
      streaming: '流式推理',
    },
    weightDtype: '权重精度',
    kvDtype: 'KV Cache 精度',
    inputAvg: '输入 Token (平均)',
    inputP95: '输入 Token (P95)',
    outputAvg: '输出 Token (平均)',
    outputP95: '输出 Token (P95)',
    concurrency: '目标并发',
    options: '推理增强项',
    optionLabels: {
      continuousBatching: 'Continuous Batching',
      pagedKvCache: 'Paged KV Cache',
      speculativeDecoding: 'Speculative Decoding',
    },
    gpuType: 'GPU 型号',
    gpuMemory: 'GPU 显存 (GB)',
    gpusPerNode: '单机 GPU 数',
    nodeCount: '节点数',
    totalGpu: '部署卡数',
    actionCopy: {
      fillModel: '请填写模型配置',
      run: '开始推理计算',
      empty: '填写上面三步后开始推理计算。',
    },
    statusCopy: {
      fit: '可部署',
      blocked: '受限',
      badgeFit: '可部署',
      badgeBlocked: '部署受限',
    },
    resultSummary: {
      deploy: '能否部署',
      concurrency: '安全并发',
      peakMemory: '峰值显存',
      parallel: '推荐并行',
    },
    memoryLayers: {
      title: '显存分层',
      weight: 'Weight',
      kv: 'KV Cache',
      runtime: 'Runtime Buffer',
    },
    mappingTitle: '机器切分映射',
    mappingDescription: '重点标出哪些卡承载权重，哪些卡承担 stage。',
    recommendationTitle: '建议',
  },
  en: {
    pageTitle: 'Inference',
    pageDescription: 'Fixed Model -> Service -> Hardware -> Result flow. The first screen answers deployability, safe concurrency, peak memory, and recommended parallel.',
    modelTitle: 'Model',
    serviceTitle: 'Service',
    hardwareTitle: 'Hardware',
    resultTitle: 'Result',
    preset: 'Model Preset',
    modelType: 'Model Type',
    modelName: 'Model Name',
    hiddenSize: 'Hidden Size',
    layers: 'Layers',
    attentionHeads: 'Attention Heads',
    kvHeads: 'KV Heads',
    ffnDim: 'FFN Intermediate',
    vocabSize: 'Vocab Size',
    moeTitle: 'MoE',
    moeFields: {
      experts: 'Experts',
      expertsPerToken: 'Experts / Token',
    },
    engine: 'Engine',
    mode: 'Mode',
    modeOptions: {
      offline: 'Offline',
      online: 'Online',
      streaming: 'Streaming',
    },
    weightDtype: 'Weight DType',
    kvDtype: 'KV Cache DType',
    inputAvg: 'Input Tokens (Avg)',
    inputP95: 'Input Tokens (P95)',
    outputAvg: 'Output Tokens (Avg)',
    outputP95: 'Output Tokens (P95)',
    concurrency: 'Target Concurrency',
    options: 'Serving Options',
    optionLabels: {
      continuousBatching: 'Continuous Batching',
      pagedKvCache: 'Paged KV Cache',
      speculativeDecoding: 'Speculative Decoding',
    },
    gpuType: 'GPU Type',
    gpuMemory: 'GPU Memory (GB)',
    gpusPerNode: 'GPUs / Node',
    nodeCount: 'Nodes',
    totalGpu: 'Serving GPUs',
    actionCopy: {
      fillModel: 'Please fill model config',
      run: 'Run inference plan',
      empty: 'Complete the first three steps and run the inference plan.',
    },
    statusCopy: {
      fit: 'Fit',
      blocked: 'Blocked',
      badgeFit: 'Deployable',
      badgeBlocked: 'Blocked',
    },
    resultSummary: {
      deploy: 'Can Deploy',
      concurrency: 'Safe Concurrency',
      peakMemory: 'Peak Memory',
      parallel: 'Recommended Parallel',
    },
    memoryLayers: {
      title: 'Memory Layers',
      weight: 'Weight',
      kv: 'KV Cache',
      runtime: 'Runtime Buffer',
    },
    mappingTitle: 'Machine Split Map',
    mappingDescription: 'Highlight which GPUs hold weights and which GPUs host stages.',
    recommendationTitle: 'Recommendations',
  },
};
