import type { LocaleCopyMap, RuntimeCopy } from './copyTypes.ts';

export const RUNTIME_COPY: LocaleCopyMap<RuntimeCopy> = {
  zh: {
    common: {
      yes: '是',
      no: '否',
      off: '关闭',
      customModel: '自定义模型',
      presetPlaceholder: '选择模型预设...',
      buffer: '缓冲区',
      cluster: '集群',
      parallel: '并行',
      used: '已使用',
      node: '节点',
      idle: '空闲',
      validation: '结构校验',
      totalGpu: '总计',
    },
    parser: {
      invalidJson: '无效的 JSON 格式',
      missingHiddenSize: '未找到 hidden_size，需要手动输入',
      missingNumHiddenLayers: '未找到 num_hidden_layers，需要手动输入',
      missingRoutedExperts: 'MoE 模型未找到 routed expert 数量，需要手动输入',
      multimodalNeedsVision: '多模态模型需要额外配置视觉编码器参数',
    },
    parallelConstraints: {
      invalidTp: 'TP 必须是大于等于 1 的整数',
      invalidPp: 'PP 必须是大于等于 1 的整数',
      invalidEp: 'EP 必须是大于等于 1 的整数',
      invalidDp: 'DP 必须是大于等于 1 的整数',
      tpMustDivide: (tpSize: number, invalidTargets: string[]) => `TP=${tpSize} 需要整除 ${invalidTargets.join('、')}`,
      tpValid: (tpSize: number, hiddenSize: number, numAttentionHeads: number, numKeyValueHeads: number) =>
        `TP=${tpSize} 可整除 hidden size ${hiddenSize}、attention heads ${numAttentionHeads} 和 KV heads ${numKeyValueHeads}`,
      ppMustDivide: (ppSize: number, numHiddenLayers: number) => `PP=${ppSize} 需要整除层数 ${numHiddenLayers}`,
      ppValid: (ppSize: number, numHiddenLayers: number) =>
        `PP=${ppSize} 可将 ${numHiddenLayers} 层均分为每段 ${numHiddenLayers / ppSize} 层`,
      epDisabled: 'EP=1，当前不启用 expert parallel',
      epOnlyForMoe: (epSize: number) => `EP=${epSize} 只适用于 MoE 模型`,
      epMustDivide: (epSize: number, expertCount: number) => `EP=${epSize} 需要整除 expert 数 ${expertCount}`,
      epValid: (epSize: number, expertCount: number) => `EP=${epSize} 可将 ${expertCount} 个 experts 均分到各并行分片`,
      hardwareExceeded: (requestedGpus: number, totalAvailableGpus: number) =>
        `当前并行配置需要 ${requestedGpus} 张 GPU，超过可用的 ${totalAvailableGpus} 张`,
      hardwareUsage: (requestedGpus: number, totalAvailableGpus: number) =>
        `当前并行配置将使用 ${requestedGpus} / ${totalAvailableGpus} 张 GPU`,
      tpCrossNode: (tpSize: number) => `TP=${tpSize} 会跨节点，通信开销会明显上升`,
      epCrossNode: (epSize: number) => `EP=${epSize} 会跨节点分布 experts，all-to-all 通信压力会增大`,
    },
    risk: {
      runnable: '可运行',
      atRisk: '有风险',
      highRisk: '高风险',
      blocked: '不可运行',
      descriptions: {
        green: '资源配置合理，可以正常运行',
        yellow: '存在一定风险，建议优化配置',
        orange: '风险较高，强烈建议调整',
        red: '配置不可行，请调整参数',
      },
      oomTitle: '显存溢出风险',
      oomDescription: (peakMemoryGb: number, gpuMemoryGb: number) => `峰值显存 ${peakMemoryGb.toFixed(1)}GB / ${gpuMemoryGb}GB`,
      oomSuggestion: '降低 micro batch size、开启 activation checkpointing 或增加 GPU 数量',
      commTitle: '通信瓶颈风险',
      commDescription: (tpSize: number, ppSize: number) => `TP=${tpSize}, PP=${ppSize} 跨节点通信`,
      commSuggestion: '将 TP 限制在单节点内，或使用 NVLink/IB 高速互联',
      actTitle: '激活显存风险',
      actDescription: (seqLen: number) => `序列长度 ${seqLen} 可能导致激活显存过大`,
      actSuggestion: '开启 selective/full recomputation 或降低序列长度',
      moeTitle: 'MoE 路由风险',
      moeDescription: (expertCount?: number) => `Expert 数量 ${expertCount}，路由通信开销较高`,
      moeSuggestion: '使用 EP 并行并限制在单节点内',
    },
    training: {
      overMemory: (requiredGb: number, limitGb: number) => `当前配置需要 ${requiredGb.toFixed(1)}GB，超过 ${limitGb}GB 限制`,
      useTensorParallel: (tpSize: number) => `建议使用 TP=${tpSize} 进行张量并行`,
      enableActivationCheckpointing: '开启 activation checkpointing 可显著降低激活显存',
      recommendedSetup: (tpSize: number, ppSize: number) => `推荐配置: TP=${tpSize}, PP=${ppSize}`,
      useLora: '或选择 LoRA 微调以降低显存需求',
      reduceActivationMemory: '开启 activation checkpointing 可进一步降低显存',
      tpCrossNode: 'TP 跨节点通信开销大，建议限制 TP 在单节点内',
      enableEp: 'MoE 模型建议开启 EP 并行',
      multimodalVision: '多模态模型需额外显存用于 vision encoder',
      ttsVocoder: 'TTS 模型需额外显存用于 vocoder',
      keepHeadroom: '显存接近上限，建议预留安全余量',
      qloraPrecision: 'QLoRA 建议使用 BF16 或 FP16 精度',
    },
    inference: {
      minDeployFail: '当前权重与运行时缓存已超过单卡显存，需增加 TP/PP、降低权重量化精度，或更换更大显存 GPU',
      minDeployTag: '单卡不满足最低部署条件',
      reduceConcurrency: (target: number, safe: number) => `建议将并发从 ${target} 调整到 ${safe}`,
      concurrencyTag: '并发超限',
      int8Kv: 'KV Cache 使用 INT8 可显著降低显存占用',
      enableContinuousBatching: '建议开启 continuous batching 提升并发效率',
      continuousBatchingTag: '连续批处理建议',
      enablePagedKv: '建议开启 paged KV cache 优化显存利用率',
      pagedKvTag: '分页KV缓存建议',
      memoryRiskTag: '显存风险',
      kvRiskTag: 'KV缓存风险',
    },
    shared: {
      suggestionPrefix: '建议',
      recommendationTitle: '建议与风险提示',
      recommendationDescription: '先处理红色风险，再对黄色项做成本与速度权衡。',
      parallelTitle: '推荐并行策略',
      parallelDescription: '将计算切分方式和实际 GPU 规模放在一起看，避免只看到 TP/PP 数字却忘了总卡数约束。',
      zeroLabel: 'ZeRO',
      throughputLabel: '吞吐',
      throughputDescription: '输出区间代表理想与保守估计，适合先做第一轮预算。',
      throughputRange: (min: number, max: number) => `区间: ${min.toLocaleString()} - ${max.toLocaleString()} tok/s`,
      estimatedTime: (time: string) => `预计时长: ${time}`,
      machineTitle: '机器切分映射',
      machineDescription: 'TP / PP / DP / EP 在当前机器配置上的落位关系。',
      legend: {
        weight: '权重',
        stage: '阶段',
        replica: '副本',
        expert: '专家',
      },
      trainNote: '训练图重点看副本、stage 和每卡状态落位。',
      inferNote: '推理图重点看权重承载卡和 stage 分布。',
      layersPerStage: (layersPerStage: number) => `每个 stage 约 ${layersPerStage} 层。`,
      noPipeline: '当前未启用 pipeline stage 切分。',
      expertsPerShard: (expertCount: number, epSize: number) =>
        `${expertCount} experts / ${epSize} = ${Math.floor(expertCount / epSize)} experts per shard.`,
      noExpertParallel: '当前不启用 expert parallel。',
    },
    memoryBar: {
      title: '显存占用',
      description: '按组件查看峰值构成，而不是只看单个总数。',
      params: '参数',
      grads: '梯度',
      optimizer: '优化器',
      activation: '激活',
      buffer: '缓冲区',
      weights: '权重',
      kvCache: 'KV Cache',
    },
  },
  en: {
    common: {
      yes: 'Yes',
      no: 'No',
      off: 'Off',
      customModel: 'Custom Model',
      presetPlaceholder: 'Select preset...',
      buffer: 'Buffer',
      cluster: 'Cluster',
      parallel: 'Parallel',
      used: 'Used',
      node: 'Node',
      idle: 'Idle',
      validation: 'Structure Validation',
      totalGpu: 'Total',
    },
    parser: {
      invalidJson: 'Invalid JSON format',
      missingHiddenSize: 'Missing hidden_size. Please fill it manually.',
      missingNumHiddenLayers: 'Missing num_hidden_layers. Please fill it manually.',
      missingRoutedExperts: 'Missing routed expert count for the MoE model. Please fill it manually.',
      multimodalNeedsVision: 'Multimodal models need extra vision encoder settings.',
    },
    parallelConstraints: {
      invalidTp: 'TP must be an integer >= 1',
      invalidPp: 'PP must be an integer >= 1',
      invalidEp: 'EP must be an integer >= 1',
      invalidDp: 'DP must be an integer >= 1',
      tpMustDivide: (tpSize: number, invalidTargets: string[]) => `TP=${tpSize} must divide ${invalidTargets.join(', ')}`,
      tpValid: (tpSize: number, hiddenSize: number, numAttentionHeads: number, numKeyValueHeads: number) =>
        `TP=${tpSize} divides hidden size ${hiddenSize}, attention heads ${numAttentionHeads}, and KV heads ${numKeyValueHeads}`,
      ppMustDivide: (ppSize: number, numHiddenLayers: number) => `PP=${ppSize} must divide layer count ${numHiddenLayers}`,
      ppValid: (ppSize: number, numHiddenLayers: number) =>
        `PP=${ppSize} splits ${numHiddenLayers} layers into ${numHiddenLayers / ppSize} layers per stage`,
      epDisabled: 'EP=1 keeps expert parallel disabled',
      epOnlyForMoe: (epSize: number) => `EP=${epSize} only applies to MoE models`,
      epMustDivide: (epSize: number, expertCount: number) => `EP=${epSize} must divide expert count ${expertCount}`,
      epValid: (epSize: number, expertCount: number) => `EP=${epSize} splits ${expertCount} experts evenly across shards`,
      hardwareExceeded: (requestedGpus: number, totalAvailableGpus: number) =>
        `Current parallel config requires ${requestedGpus} GPUs, exceeding the available ${totalAvailableGpus}`,
      hardwareUsage: (requestedGpus: number, totalAvailableGpus: number) =>
        `Current parallel config uses ${requestedGpus} / ${totalAvailableGpus} GPUs`,
      tpCrossNode: (tpSize: number) => `TP=${tpSize} crosses nodes and will increase communication cost`,
      epCrossNode: (epSize: number) => `EP=${epSize} spreads experts across nodes and increases all-to-all pressure`,
    },
    risk: {
      runnable: 'Runnable',
      atRisk: 'At Risk',
      highRisk: 'High Risk',
      blocked: 'Blocked',
      descriptions: {
        green: 'The resource setup looks healthy and should run normally.',
        yellow: 'There is some risk. The configuration should be reviewed.',
        orange: 'The risk is high. Strongly consider adjusting the setup.',
        red: 'The configuration is not feasible. Adjust the parameters first.',
      },
      oomTitle: 'Out-of-memory risk',
      oomDescription: (peakMemoryGb: number, gpuMemoryGb: number) => `Peak memory ${peakMemoryGb.toFixed(1)}GB / ${gpuMemoryGb}GB`,
      oomSuggestion: 'Lower the micro batch size, enable activation checkpointing, or add more GPUs',
      commTitle: 'Communication bottleneck risk',
      commDescription: (tpSize: number, ppSize: number) => `TP=${tpSize}, PP=${ppSize} crosses node boundaries`,
      commSuggestion: 'Keep TP within a single node or use faster interconnect such as NVLink/IB',
      actTitle: 'Activation memory risk',
      actDescription: (seqLen: number) => `Sequence length ${seqLen} may push activation memory too high`,
      actSuggestion: 'Enable selective/full recomputation or lower the sequence length',
      moeTitle: 'MoE routing risk',
      moeDescription: (expertCount?: number) => `Expert count ${expertCount} may increase routing communication`,
      moeSuggestion: 'Use EP and keep it within a single node when possible',
    },
    training: {
      overMemory: (requiredGb: number, limitGb: number) => `Current config needs ${requiredGb.toFixed(1)}GB, above the ${limitGb}GB limit`,
      useTensorParallel: (tpSize: number) => `Use TP=${tpSize} for tensor parallelism`,
      enableActivationCheckpointing: 'Enable activation checkpointing to cut activation memory',
      recommendedSetup: (tpSize: number, ppSize: number) => `Recommended setup: TP=${tpSize}, PP=${ppSize}`,
      useLora: 'Or switch to LoRA fine-tuning to reduce memory needs',
      reduceActivationMemory: 'Enable activation checkpointing to further reduce memory',
      tpCrossNode: 'TP crosses node boundaries; keep TP within one node if possible',
      enableEp: 'MoE models should consider enabling EP',
      multimodalVision: 'Multimodal models need extra memory for the vision encoder',
      ttsVocoder: 'TTS models need extra memory for the vocoder',
      keepHeadroom: 'Memory is close to the limit. Keep some safety headroom.',
      qloraPrecision: 'QLoRA works best with BF16 or FP16',
    },
    inference: {
      minDeployFail: 'Weights plus runtime buffers already exceed single-GPU memory. Increase TP/PP, lower weight precision, or use GPUs with more memory.',
      minDeployTag: 'Single-GPU minimum deployment does not fit',
      reduceConcurrency: (target: number, safe: number) => `Reduce concurrency from ${target} to ${safe}`,
      concurrencyTag: 'Concurrency exceeds the memory budget',
      int8Kv: 'INT8 KV cache can significantly reduce memory usage',
      enableContinuousBatching: 'Enable continuous batching to improve concurrency efficiency',
      continuousBatchingTag: 'Continuous batching recommended',
      enablePagedKv: 'Enable paged KV cache to improve memory efficiency',
      pagedKvTag: 'Paged KV cache recommended',
      memoryRiskTag: 'Memory risk',
      kvRiskTag: 'KV cache risk',
    },
    shared: {
      suggestionPrefix: 'Suggestion',
      recommendationTitle: 'Recommendations and Risks',
      recommendationDescription: 'Resolve red risks first, then trade off yellow items against cost and speed.',
      parallelTitle: 'Recommended Parallel Strategy',
      parallelDescription: 'View the split strategy next to the actual GPU budget so TP/PP numbers stay grounded in cluster size.',
      zeroLabel: 'ZeRO',
      throughputLabel: 'Throughput',
      throughputDescription: 'The range shows optimistic and conservative estimates for a first-pass budget.',
      throughputRange: (min: number, max: number) => `Range: ${min.toLocaleString()} - ${max.toLocaleString()} tok/s`,
      estimatedTime: (time: string) => `Estimated time: ${time}`,
      machineTitle: 'Machine Split Map',
      machineDescription: 'Placement of TP / PP / DP / EP on the current machine layout.',
      legend: {
        weight: 'weight',
        stage: 'stage',
        replica: 'replica',
        expert: 'expert',
      },
      trainNote: 'Training view emphasizes replicas, stages, and per-GPU state placement.',
      inferNote: 'Inference view emphasizes weight-carrying GPUs and stage placement.',
      layersPerStage: (layersPerStage: number) => `About ${layersPerStage} layers per stage.`,
      noPipeline: 'Pipeline stage splitting is not enabled.',
      expertsPerShard: (expertCount: number, epSize: number) =>
        `${expertCount} experts / ${epSize} = ${Math.floor(expertCount / epSize)} experts per shard.`,
      noExpertParallel: 'Expert parallel is not enabled.',
    },
    memoryBar: {
      title: 'Memory Usage',
      description: 'Break peak memory down by component instead of looking only at the total.',
      params: 'Params',
      grads: 'Grads',
      optimizer: 'Optimizer',
      activation: 'Activation',
      buffer: 'Buffer',
      weights: 'Weights',
      kvCache: 'KV Cache',
    },
  },
};
